### PR TITLE
docs: non-nix users support

### PR DESCRIPTION
**Pull request by gvolpe**
@NotAShelf I've requested Garnix access to this repo, so we can keep the current CI/CD workflows.

### CODE REVIEW

**Review by NotAShelf — APPROVED** [review]
LGTM

**Comment by gvolpe** [comment]
I can't merge until permissions are granted to Garnix though, I've initiated a request, any admin of the org should be able to approve. Thanks 🙏🏽

**Comment by NotAShelf** [comment]
Quite frankly I do not trust Garnix (still have no idea who is behind it, what their motives are or whether they can be trusted) but I also do not want to force anyone to our Cachix instance.

Once I get the notification, I'll approve it. Or maybe @yavko can if I don't get the chance over the next few days.

**Comment by NotAShelf** [comment]
Okay, looks like it's installed now. Let me know if there's anything else.

**Comment by gvolpe** [comment]
> Quite frankly I do not trust Garnix (still have no idea who is behind it, what their motives are or whether they can be trusted) but I also do not want to force anyone to our Cachix instance.

Valid concern, though the access permission is just for this repository, not for the entire organization. One could think the same about Cachix too, unless you run your own instance? :)

**Review by yavko — APPROVED** [review]

**Comment by yavko** [comment]
Idk why I reviewed after it was merged but github was begging me to.

**Pull request merged**
